- name: creating 8 small vms
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
  - name: boot 8 vms
    shell: for i in `seq {{num}}` ; do nova boot --flavor {{flavor}} --image futuresystems/ubuntu-14.04 --key_name $USER-id_rsa {{name}}-$i;done
    register: nova 
  - debug: var=nova.stdout_lines

  - name: getting ip addresses
    shell: while [ `nova list|grep {{name}}|cut -d'|' -f4|tr -d ' '|grep ACTIVE|wc -l` != "{{num}}" ]; do sleep 1; done; nova list|grep {{name}}-[1-{{num}}]|cut -d'|' -f7|cut -d"=" -f2 > inventory-{{name}}.txt
  
