- hosts: ansible-test
  remote_user: ubuntu
  tasks:
    - name: get ip address
      shell: ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/' > ~/.ipaddr
    - name: update hosts
      shell: sudo su -c "echo `cat /home/ubuntu/.ipaddr` `hostname` >> /etc/hosts"
      #shell: ls

